version: '3.9'

services:
    nginx:
        build: ./nginx/
        container_name: nginx-container
        restart: always
        ports:
            - "8097:80"
        links: 
            - php
        volumes_from:
            - app-data
    
    php:
        build: ./php/
        container_name: php-container
        expose:
            - 9000
        volumes_from:
            - app-data

    app-data:
        image: php:8.1-fpm
        container_name: app-data-container
        volumes:
            - ./www/html/:/var/www/html/
        command: "true"